package day45_exceptions1;

public class C01_TryCatch {
    public static void main(String[] args) {
        int number1 = 20;
        int number2 = 0;

        /*
        When we write codes. If we can for see a problem before it happens
        we can try-catch to offer a solution for that problem.
        As a result java can continue to run.
           */



        //try
        System.out.println(number1/number2); //ArithmeticException

        //catch(){}

        System.out.println("code ended here");


    }



}
